feat(ci): create PR if CI checked (#118)
* feat: add 42sh & .log

* fix(ci): allow push to mirror only on main branch

* fix(exec): add newline to error messages for clarity

* feat(ci): create PR if CI checked

* fix(ci): update create PR on push

* fix(ci): add robustness if PR already exist

---------

Co-authored-by: ErwanTheGoat <erwan.lo-presti@epitech.eu>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -153,6 +153,41 @@ jobs:
         run: make tests_run
         timeout-minutes: 2
   
+  merge_to_main:
+    if: github.ref == 'refs/heads/dev' && github.event_name == 'push'
+    needs:
+      - check_mirror
+      - run_tests
+    runs-on: ubuntu-latest
+    permissions:
+      pull-requests: write
+      contents: read
+    steps:
+      - uses: actions/checkout@v6
+        with:
+          fetch-depth: 0
+
+      - name: Get body content
+        id: pr_body
+        run: |
+          echo "COMMITS_LIST<<EOF" >> $GITHUB_ENV
+          echo "### List of changements: " >> $GITHUB_ENV
+          git log origin/main..HEAD --oneline --pretty=format:"- %s (%h)" >> $GITHUB_ENV
+          echo "" >> $GITHUB_ENV
+          echo "EOF" >> $GITHUB_ENV
+
+      - name: Create PR dev -> main
+        run: |
+          gh pr create \
+            --title "Update: ${{ github.ref_name }}" \
+            --body "$COMMITS_LIST" \
+            --reviewer "lukas-sgx,copilot" \
+            --base main \
+            --head dev || echo "PR already exists or could not be created"
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+    
+  
   push_to_mirror:
     if: github.ref == 'refs/heads/main' && github.event_name == 'push'
     needs:
